name: harvest (dev mode supabase)

on:
  push:
    branches:
      - master
  workflow_dispatch:
  # https://crontab.guru/#30_5_*_*_*
  schedule:
    - cron: "30 5 * * *"
jobs:
  dev-harvest:
    environment: remote-development-supabase-v3
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - name: Get the source
        uses: actions/checkout@v3
      - name: Harvester Action
        uses: ./
        id: harvester
        with:
          PG_SERVER: ${{ secrets.PG_SERVER }}
          PG_PORT: ${{ secrets.PG_PORT }}
          PG_USER: ${{ secrets.PG_USER }}
          PG_PASS: ${{ secrets.PG_PASS }}
          PG_DB: ${{ secrets.PG_DB }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID}}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          OUTPUT: "True"
          LOGGING: "INFO"
          MAPBOXUSERNAME: ${{ secrets.MAPBOXUSERNAME }}
          MAPBOXTOKEN: ${{ secrets.MAPBOXTOKEN }}
          MAPBOXTILESET: ${{ secrets.MAPBOXTILESET }}
          MAPBOXLAYERNAME: ${{ secrets.MAPBOXLAYERNAME }}
